### ISSUE TITLE
Undefined error when importing the library. Additionally, the documentation is confusing.

### ISSUE THREAD

**Issue by aaronchristian99** [mbj36/vue-burger-menu#143]
I went exactly as it said in the documentation. This is the code - 

`<Slide
            :isOpen="openMenu"
            right
            :closeOnNavigation="true"
            :burgerIcon="false"
            @openMenu="handleOpenMenu"
            @closeMenu="handleCloseMenu">
            <RouterLink to="/benefits">Benefits</RouterLink>
            <RouterLink to="/features">Features</RouterLink>
            <RouterLink to="/about-us">Behind Wijs</RouterLink>
            <RouterLink to="/demo-library">Demo Library</RouterLink>
            <RouterLink to="/book-a-demo">Book Demo</RouterLink>
            <RouterLink to="/pricing">Pricing</RouterLink>
            <RouterLink to="/contact">Contact</RouterLink>
        </Slide>`

with import statement in script - 

`import { Slide } from 'vue-burger-menu';`

I am getting the error - 

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (vue-burger-menu.common.js:2120:66)
    at renderComponentRoot (runtime-core.esm-bundler.js:896:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5575:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:185:1)
    at instance.update (runtime-core.esm-bundler.js:5689:1)
    at setupRenderEffect (runtime-core.esm-bundler.js:5703:1)
    at mountComponent (runtime-core.esm-bundler.js:5485:1)
    at processComponent (runtime-core.esm-bundler.js:5443:1)
    at patch (runtime-core.esm-bundler.js:5033:1)
    at mountChildren (runtime-core.esm-bundler.js:5229:1)
render @ vue-burger-menu.common.js:2120
renderComponentRoot @ runtime-core.esm-bundler.js:896
componentUpdateFn @ runtime-core.esm-bundler.js:5575
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
mountChildren @ runtime-core.esm-bundler.js:5229
mountElement @ runtime-core.esm-bundler.js:5138
processElement @ runtime-core.esm-bundler.js:5110
patch @ runtime-core.esm-bundler.js:5030
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
setupRenderEffect @ runtime-core.esm-bundler.js:5703
mountComponent @ runtime-core.esm-bundler.js:5485
processComponent @ runtime-core.esm-bundler.js:5443
patch @ runtime-core.esm-bundler.js:5033
mountChildren @ runtime-core.esm-bundler.js:5229
processFragment @ runtime-core.esm-bundler.js:5402
patch @ runtime-core.esm-bundler.js:5026
componentUpdateFn @ runtime-core.esm-bundler.js:5582
run @ reactivity.esm-bundler.js:185
instance.update @ runtime-core.esm-bundler.js:5689
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:396
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:285
queueJob @ runtime-core.esm-bundler.js:279
reload @ runtime-core.esm-bundler.js:530
eval @ runtime-core.esm-bundler.js:568
eval @ Header.vue:13
./resources/js/components/layouts/Header.vue @ app.js:1522
__webpack_require__ @ app.js:3149
_requireSelf @ app.js:3430
apply @ app.js:4222
(anonymous) @ app.js:3672
internalApply @ app.js:3670
(anonymous) @ app.js:3607
waitForBlockingPromises @ app.js:3561
(anonymous) @ app.js:3605
Promise.then (async)
(anonymous) @ app.js:3604
Promise.then (async)
(anonymous) @ app.js:3584
Promise.then (async)
hotCheck @ app.js:3575
check @ dev-server.js:15
eval @ dev-server.js:69
emit @ events.js:153
reloadApp @ reloadApp.js:38
ok @ index.js:227
eval @ socket.js:62
client.onmessage @ WebSocketClient.js:45`

**Comment by agbert** [comment]
Is anyone paying attention to this persistent issue?
